appid: leanfried.sbgui.v1.0.5
camera:
  cam0:
    checked: false
    diag: 1
    flag1: 3
    fps: 30
    name: Basler camera
    previewFPS: 15
    type: bascam
  cam1:
    checked: false
    diag: 1
    flag1: 5
    fps: 15
    name: Nozzle camera
    previewFPS: 15
    type: webcam
  cam2:
    checked: false
    diag: 1
    flag1: 6
    fps: 15
    name: Webcam 2
    previewFPS: 15
    type: webcam
files:
  createSubfolders: true
  dateFormat: '%y%m%d'
  duplicateFormat: '{0:0=3d}'
  includeDateRadio: 0
  includeSBInFile: true
  includeSBRadio: 1
  includeSampleInFile: true
  includeSampleInFolder: true
  includeTimeInFile: true
  save: C:\Users\lmf1\Documents\Shopbot videos\test
  separator: _
  tag: test
  timeFormat: '%y%m%d_%H%M%S_%f'
fluigent:
  channel0:
    calibration:
      flowRateFolder: C:/Users/lmf1/OneDrive - NIST/NIST/data/material properties/flow
        rates
      initDensity: 1
      initDiam: 0.603
      initSpeed: 10.0
    color: '#5a8171'
    flag1: 1
  channel1:
    calibration:
      flowRateFolder: C:/Users/lmf1/OneDrive - National Institute of Standards and
        Technology (NIST)/NIST/data/material properties/flow rates
      initDensity: 1
      initDiam: 0.603
      initSpeed: 5.0
    color: '#b0401e'
    flag1: 2
  dt: 100
  pmax: 2000
  savePressure: true
  trange: 60
layout:
  save: true
meta:
  camera_magnification:
    units: x
    value: '0.5'
  camera_position:
    units: None
    value: side
  nozzle_inner_diameter:
    units: mm
    value: '0.603'
  nozzle_length:
    units: mm
    value: '38'
  nozzle_material:
    units: None
    value: stainless steel
  nozzle_outer_diameter:
    units: mm
    value: '0.908'
  tubing_inner_diameter:
    units: mm
    value: '0.79375'
  tubing_length:
    units: mm
    value: '280'
  tubing_material:
    units: None
    value: PTFE
savePressure: true
shopbot:
  autoplay: true
  burstLength: 0.01
  burstScale: 1.0
  critTimeOff: -0.2
  critTimeOn: 0.2
  currentFile: C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP_files/tripleLinesSide/crossDoubleHorizPics2.sbp
  diag: 2
  dt: 10.0
  flag1: 12
  flag1max: 12
  flag1min: 1
  includeFlagInTable: true
  includePositionInTable: true
  saveDt: 25
  savePicMetadata: true
  sbpFiles:
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP_files/tripleLinesSide/crossDoubleHorizPics2.sbp
  sbpFolder: C:\Users\lmf1\Documents\GitHub\ShopbotPyQt\SBP_files
  showFolder: false
  units: mm
  zeroDist: 0.05
testFolder: C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/pythonGUI/testResults
